source $HOME/.config/nvim/plugs.vim
source $HOME/.config/nvim/theme.vim
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/commands.vim
source $HOME/.config/nvim/mappings.vim
source $HOME/.config/nvim/filetypes.vim
source $HOME/.config/nvim/coc.vim
source $HOME/.config/nvim/telescope.vim
source $HOME/.config/nvim/vgit.vim
source $HOME/.config/nvim/lspconfig.vim
source $HOME/.config/nvim/nerdcommenter.vim
